# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MAD": "00_stats.ipynb",
         "Tukey": "00_stats.ipynb",
         "smad": "01_timeseries.ipynb",
         "plot_anomalies": "03_utils.ipynb"}

modules = ["stats.py",
           "timeseries.py",
           "forecast.py",
           "utils.py"]

doc_url = "https://fillipedem.github.io/pyanomaly/"

git_url = "https://github.com/fillipedem/pyanomaly/tree/master/"

def custom_doc_links(name): return None
